### ISSUE TITLE
NetCore support

### ISSUE THREAD

**Issue by shawnmclean** [watson-developer-cloud/dotnet-standard-sdk#100]
Are there any plans to support netcoreapp?

I looked into the code for the upgrade path and found that there may be some code changes required. 

The most major change I've noticed is the removal of `System.Net.Http.Formatting`. Your code depends on this for serialization formats, it may be possible to rewrite these sections using strings and determine the serialization type manually.

I could pick up this task if you guys wish.

**Comment by mediumTaj** [comment]
Sure, we can use all the help we can get! @atilatosta can you keep an eye on this?

**Comment by atilatosta** [comment]
@shawnmclean, @mediumTaj  hi guys! We are trying to solve the Xamarin support problem and we believe that it solves this problem as well. If the problem is not solved, we will be very happy if you can help us. We are testing in a local repository. I believe we have an answer by Friday. I'll let you know around here.

**Comment by mat0pad** [comment]
Any news on this?

**Comment by mediumTaj** [comment]
Nothing yet, @atilatosta is looking into it.
