### ISSUE TITLE
[Speech-to-text] The service always returns Speaker "0".

### ISSUE THREAD

**Issue by ShotiQ** [watson-developer-cloud/dotnet-standard-sdk#149]

**Comment by atilatosta** [comment]
@ShotiQ hi! Please, Could you provide a description?

### When reporting a bug, please be sure to include the following:

- [ ] Start the title with the service name in brackets:  `[speech-to-text] websockets...`
- [ ] Steps to reproduce
- [ ] Expected behavior
- [ ] Actual behavior
- [ ] SDK version

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title starting with the service name
- [ ] A description of the problem you're trying to solve
- [ ] A suggested solution if possible
