### ISSUE TITLE
Why not typed classes (Conversation)

### ISSUE THREAD

**Issue by xjose97x** [watson-developer-cloud/dotnet-standard-sdk#209]
I've checked that the MessageResponse class in the Conversation Library has dynamic properties. Why have as dynamic instead of typed classes?

**Comment by xjose97x** [comment]
I noticed that in previous versions we used classes such as RuntimeEntity, RuntimeIntent, RuntimeOutput, etc. That worked pretty well.

**Comment by mediumTaj** [comment]
Hi @xjose97x ,
There is a requirement that users be able to pass custom data through the Conversation service. The Watson SDKs are now completely generated from the [swagger](https://watson-api-explorer.mybluemix.net/) so all of the SDKs are consistent.

Closing this issue since it's not a problem with the SDK.
